on: [ push ]
name: Build/Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Checkout code
        uses: actions/checkout@master

      - name: Run tests
        run: |
          make test-ci COVERAGE=codecov

      - name: Generate coverage report
        if: github.ref == 'refs/heads/main'
        run: |
          make generate-coverage-report

      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: nongenerated_code.cov
